### ISSUE TITLE
mobile - hero section

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#1]
The current hero image is full screan. It eats the total above the fold part. 
I would suggest to use smaller, like 75%, 50% or 30% of above the fold.

**Comment by Sukhayanti** [comment]
I still do not agree... So how are we going to solve this?

**Comment by rrd108** [comment]
I made an alternate home page with a smaller hero section. It is rough but you can see the difference.

**Comment by Sukhayanti** [comment]
I asked my father and Nila and they both preferred the bigger hero image. 
They also preferred the picture of scenery for the hero image. 
I put the same hero image for both versions so the different image will not be a factor in their impression. 
I say, keep the larger hero image

**Comment by rrd108** [comment]
Perhaps they do not dare to vote against you.

But ok keep the full screen layout.

But change it to something attractive.

**Comment by Sukhayanti** [comment]
Apparently you do not know my father... You think I'm hard person? Wait until you get to know my dad. His honesty knows no bounds.

I'll keep it 😁

I like the picture .. but I'll try to find another one. But smiling people for the hero image though

**Comment by rrd108** [comment]
Can you replace the current one with the new one with the 3 buttons?

**Comment by Sukhayanti** [comment]
New version available. The arrow leads to the service section #4
