### ISSUE TITLE
új honlap fesztivál feltöltése

### ISSUE THREAD

**Issue by Kundalata** [rrd108/krisnavolgy#112]
nem tudok képet feltölteni, a galéria a meglévő eddig feltöltött képeket adja csak be, a varázspálca meg csak teker...

**Comment by rrd108** [comment]
Ez nekem úgy hangzik mintha menet közben elveszett volna az internet.
Megpróbálná megint?

**Comment by Kundalata** [comment]
ugyanúgy nincs törlés, stb. Majd személyesen egyszer megmutatom, meg azért kis oktatás még kellene nekem, hogy mik a funkciók, sok duplikáció volt ...
