### ISSUE TITLE
ökrösszekér túra rendelés - új téma

### ISSUE THREAD

**Issue by Kundalata** [rrd108/krisnavolgy#122]
ttps://krisnavolgy.hu/okrosturak/ - ez van most kint

még valahova a csoport oldalra be lehetne tenni ezt, akár csak link: **ökrösszekér túra rendelés**
![Ökrösszekér Túrák banner](https://github.com/user-attachments/assets/51ac168a-09cd-454b-9554-b2d22d04c5b5)

**Comment by rrd108** [comment]
Ezt ha valaki leírja nekem szövegesen akkor felteszem

**Comment by Kundalata** [comment]
**Ökrösszekér túrák egyedi megrendelésre**

Családi Kalandtúra Krisna-völgyben.

Az Ökrösszekerezés 45 perces, max 10 főre rendelhető, 18.000 Ft/ szekér (max 10 fő)

Rendelés:
Kósa Antal
Anthardi Dász
30/213-9831
antardhi@krisna.hi
