### ISSUE TITLE
NYITÓ OLDALON javítások... "futó ajánló buborékok"

### ISSUE THREAD

**Issue by Kundalata** [rrd108/krisnavolgy#126]
Ezek mindegyike tartalmaz tól-ig árakat, itt én lecserélném pár helyen az árakat egyéb infóra - félrevezető lehet pl étterem legolcsóbb terméknél, hogy ő jött 190 Ft-ért enni, mert ez volt kiírva :-)

javaslatok:
étterem: **vegán és vegetáriánus finomságok**
elvonulás: **Hatha-jóga, meditáció...**

**Comment by rrd108** [comment]
Eredetileg is ezt akartuk, hogy itt legyen egy gyors tájékoztatás az árakról.

A számokat kell kijavítani, ha megadja őket átírom

**Comment by Kundalata** [comment]
Étterem árak: 2.990 Ft - 5.890 Ft 
Elvonulás árak: 57.600 Ft - 287.500 Ft
