### ISSUE TITLE
counters

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#13]
what happens when a user clicks on them?

**Comment by Sukhayanti** [comment]
Nothing. This is just a nice visual addition to the website. 
The numbers start counting up once someone opens the website until they reach the number set by us as the total amount of that category. then the numbers just stay at the max if the guest remains on that part of the page for  longer.

**Comment by rrd108** [comment]
add javascript upcount

**Comment by Sukhayanti** [comment]
I think this is done?
