### ISSUE TITLE
árkalkulátor - étterem

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#158]
Az éttermes rendelések még ezek lennének:
Szerzetes menü 2.510 ft
Napi menü 3.140 Ft

_Originally posted by @Kundalata in https://github.com/rrd108/krisnavolgy/issues/60#issuecomment-2561039883_

**Comment by rrd108** [comment]
itt nincs gyerek kedvezmény? nyugdíjas?

**Comment by Kundalata** [comment]
Nincs, ez a 2 ár van. Illetve legyen 3. Opció, nem kérek étkezést...
