### ISSUE TITLE
Add newsletter subscription

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#19]
It should be highlighted

**Comment by Sukhayanti** [comment]
Done, added a subscribe button to the footer and an icon to the hamburger menu

**Comment by rrd108** [comment]
🤯
Newsletter subscription is one of the most imprtant thing what we should do with our webpage. I know I did not managed to convince anybody about this and I am terrible sorry for this.

It suppused to be at a very viewable part, not hidden somewhere in the menu and in the footer.

**Comment by Sukhayanti** [comment]
Done, some parts of the section is hidden behind the menu so please scroll down to see it
