### ISSUE TITLE
add a page type

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#29]
we should have a content type with some sample data to store the pages like what we have on the figma plan

**Comment by Sukhayanti** [comment]
I don't understand

**Comment by rrd108** [comment]
We should have a place where the content manager can add content. Like pages in wp

**Comment by Sukhayanti** [comment]
But don't they just add content on the pages I will construct for them?
I don't understand what content they will add here and for what purpose
therefore I don't understand what elements I should add.

**Comment by rrd108** [comment]
> But don't they just add content on the pages I will construct for them?

yes. You have to construct them. This is my request.

**Comment by Sukhayanti** [comment]
Oh!!! So you want me to start creating an the pages I created in figma???
I should create them as single not collective

**Comment by rrd108** [comment]
yes

**Comment by Sukhayanti** [comment]
Now I get it.
Ok, I'll create all the other pages of the website as they appear on figma
in strapi.
Got it!
Thanks
