### ISSUE TITLE
Service section content 

### ISSUE THREAD

**Issue by Sukhayanti** [rrd108/krisnavolgy#4]
Waiting to see how you want to solve your unsatisfaction....

**Comment by rrd108** [comment]
V2 what you did adds a new click to the user story what should be avoided. Each click drops about 30% of the users.

I was thinking about it and I v1 is ok.

Actually what I am missing and wanted to add here is featured things. Like currently we have no place in the layout for highlighting next retreat, most hot product of the webshop, last minute booking for the guesthouse.

Only the upcoming events are dynamic, all the other parts are static content. As this is the main page we should use it in a more dynamic way. It is better for UX, SEO and conversions.

Upcoming events is exactly what we need. But what about all the other highlighted services? We should have them on the main page viewable without any click.

So maybe we should separate the current section into 2.

One for static content, like prices, group programs, restaurant and one for services which has highlightable offers, liek retreats, guesthouse, webshop, festivals.

**Comment by Sukhayanti** [comment]
V2 deleted.

I added a new section, specials section, it can show 2 specials at one time. Design needs work... 

I took out the calendar view, it felt redundant and I really didn't like the design.  I can put it back in if you think it is helpful but I will change the design. We have a calendar view on the programok page

**Comment by rrd108** [comment]
> I took out the calendar view, it felt redundant and I really didn't like the design. I can put it back in if you think it is helpful but I will change the design. We have a calendar view on the programok page

Please keep comments at the issue where they belongs to

**Comment by Sukhayanti** [comment]
Is this finished?
