### ISSUE TITLE
events_section main title

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#45]
On the plan we had a main title for this block

Now it is missing from starpi

**Comment by Sukhayanti** [comment]
I do not know what you are talking about but I changed it to happening. Please let me know if it is ok the way it is now

**Comment by rrd108** [comment]
![Képernyőkép ekkor: 2023-07-01 10-59-50](https://github.com/rrd108/krisnavolgy/assets/3147489/58b3ffc5-344d-4386-8962-87136fa23be4)

The text what I marked is not coming from starpi right now, but it should

**Comment by Sukhayanti** [comment]
Done
