### ISSUE TITLE
Names of pages

### ISSUE THREAD

**Issue by Sukhayanti** [rrd108/krisnavolgy#49]
You told me to name everything in English, but I think the page names should be in Hungarian as the slug which is auto generated from Strapi does so according to the single type name.
So for example, now home page is the name of the main page and the slug is home-page....
Shouldn't it be Főoldal?

**Comment by rrd108** [comment]
Keep it as it is.

You can add a new text box: pageName or something and give the huna name for it. Than I can use it for SEO

**Comment by Sukhayanti** [comment]
But for Hungarians it will be strange to type in English slugs. Like at the
guesthouse website there is accommodation page. It is easier to tell a
Hungarian to write in the website url /szallas then /accommodation
