### ISSUE TITLE
Upcoming Events

### ISSUE THREAD

**Issue by Sukhayanti** [rrd108/krisnavolgy#5]
1. Upcoming events section - the events should be scrollable, Current events show up first (or the next 3 events to come up even if now is for example December and the next event is only April) then the user an scroll up or down for previous or upcoming events.

**Comment by rrd108** [comment]
what happens when a user clicks on an event?

**Comment by Sukhayanti** [comment]
1. The background image of the section changes to the image of that particular event.
2. The featured event picture changes to include that image of the event, its name and date
3. When clicking on the featured event box the guest will be transferred to the event page where a longer description can be found and where one can register online with or without payment (I would suggest all events will be products that can be purchased and paid online)

**Comment by Sukhayanti** [comment]
It is not really an extra click. They click on an event and the featured event changes, they click on another event and it changes again, and so on.... If when they click on an event it immediately opens on another page then we lose the guest on the home page. Like this they can quickly see what an event looks like with an image and date and perhas then we should add 2-3 summarized description about the event to give them an better idea what it is about. Then if it doesn't sound good, they can go look for a different event from the list. If they are really interested then they press on the event and it takes them to event page that has more details and purchase options.
Updated on figma

**Comment by rrd108** [comment]
then #12 featured events should have a "tovább" CTA

**Comment by Sukhayanti** [comment]
Is it necessary. Many times there are elements that do not have a CTA on it but when you hover on it, it changes and the curser  
changes and then the guest understands that it is clickable.

**Comment by rrd108** [comment]
On mobile there is no hover

**Comment by Sukhayanti** [comment]
I added a button to the services as V1.
V2 is that we have a smaller view for services with an arrow, once they click on the arrow the section will expand like a opening of a tab element. I have added V2 to figma

**Comment by Sukhayanti** [comment]
Is this finished?
