### ISSUE TITLE
strapi set limit

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#50]
we should set up limits to all fileds, like length of strings, size of images, etc

**Comment by Sukhayanti** [comment]
I did that. I googles maximum character lengths for title, and different fields and then entered those numbers as the maximum length but if you have an idea what should be the maximum length then I can change it.
As for images, I can only edit what media file can be uploaded but not their size.

- Title max - 60 characters
- sub title max - 90 characters
- short description max - 160 characters
- long description max - 550 characters 
- button text max - 20 characters

![Screenshot (253)](https://github.com/rrd108/krisnavolgy/assets/120935590/b8132327-18d0-41e1-9e96-1d8d1ffda781)
