### ISSUE TITLE
Relation selection field is showing IDs instead of names

### ISSUE THREAD

**Issue by Sukhayanti** [rrd108/krisnavolgy#51]
We need the names to show, not the ID. I found a solution but when I went to try and use it I did not have the Entry title field show up so I do not know how to solve this. 
![Screenshot (251)](https://github.com/rrd108/krisnavolgy/assets/120935590/e3d7e565-942f-4177-8696-9692885dad8f)
 

https://forum.strapi.io/t/relation-selection-field-is-showing-ids-instead-of-names/21068

**Comment by thomashisgithub** [comment]
Can you write step by step how to reproduce this bug?
