### ISSUE TITLE
Happenings - Main Menu different setup

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#52]
On the frontend side I should define in what shape the data will arrive.
I have created 2 general types, one for a single type response (like home page) and one for collection type response (like main menu).

Happenings is also a collection type but done differently then main menu. On Strapi adminat main menu it shows there is 7 menu items in it, but in Happenings they are listed. So it seems you created them differently. Because of this I get a different data format at the client side. The problem is that at the frontend side I can not detect and check what format will I receive.

So my questions are:
- Why these 2 created differently
- Can we stick to one form?
- Can we do something that later we can not use the other form?

**Comment by Sukhayanti** [comment]
- Why these 2 created differently
For the main menu I just put all menu items under the same item (one ID). For the happenings, each event has a different item (ID as well)
- Can we stick to one form?
Yes, I can create each menu item in a separate item
- Can we do something that later we can not use the other form?
I do not know and cannot find anything online for that. I looked where I create the collection type and didn't see anything in the advanced settings so if there is a way to limit it, it will be with coding I guess.

Should I change the menu that each item appears as a different item?

**Comment by rrd108** [comment]
leave it like that for now

I try to prepare frontend for both versions

**Comment by rrd108** [comment]
The  only thing I need now is to rename the block

Now it is called event_section and it should be happenings_section
