### ISSUE TITLE
Smile?

### ISSUE THREAD

**Issue by Sukhayanti** [rrd108/krisnavolgy#6]
What is this about?

**Comment by rrd108** [comment]
All pictures we use should be smiling people not empty places or buildings

**Comment by Sukhayanti** [comment]
Hmmmm... really? That's harsh. I do not have such pictures... Do you have pictures?

**Comment by rrd108** [comment]
Kundalata mataji has a lot of pictures

**Comment by Sukhayanti** [comment]
I have most of her pictures, anyway I will contact her. In any case I am closing this topic and will try to add more smiling faces. I still think that some scenery pictures can be ok for parts of the website.

**Comment by rrd108** [comment]
Please leave open issues till they are actually fixed
