### ISSUE TITLE
Árkalkulátor

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#60]
https://katicatanya.hu/arak.html

Hare Krisna, 
 
A honlapon a csoportok oldalon szeretnék egy ilyent, 😎

A csoport leírások között csak egy gomb lenne (csoportos ár kalkulátor) 

Nekem ezek kellenének:

Létszám 

Jegy típus (felnőtt, gyerek, nyugdíjas) (3.400, 2.300, 2.300)

Választott programok (felsorolás szerűen,ebből sok van 😀) 
max 2 választható (1.000 mindegyik plusz program)

Étkezés (kóstoló menü, napi menü, király menü) (2.790, 3690, 5190)

Belső parkoló használata 
Autó, busz (700, 1.400)

**Comment by Kundalata** [comment]
Választott programok (felsorolás szerűen,ebből sok van 😀)
max 2 választható (1.000 mindegyik plusz program)

és itt a FELSOROLÁS IS EHHEZ A RÉSZHEZ:

1.) Zene varázsa 
2.) Kelet divatja 
3.) Lélek hangja 
4.) Egzotikus fűszerkalauz 
5.) Életmód séta 
6.) Szerencsét hozó zarándokkörút
7.) Krisna-völgyi körséta
8.) Krisna-völgy bemutatása vallabhival  
9.) Ismerd meg krisna-völgyet - kvízjáték vallabhival 
10.) Az ökrös malom titkai

**Comment by Kundalata** [comment]
Az éttermes rendelések még ezek lennének:
Szerzetes menü 2.510 ft
Napi menü 3.140 Ft
