### ISSUE TITLE
Event calendar 

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#7]
the months should be scrollable, can go back and forward between the months

**Comment by rrd108** [comment]
what happens when a user clicks on a date?

**Comment by Sukhayanti** [comment]
A pop up appears on most of the section area on top of the calendar, let's say 70%, similar box like featured event, same design and same functionality. A close button should appear on the top right side of the pop up to allow closing it.

**Comment by rrd108** [comment]
desing it in figma then

**Comment by Sukhayanti** [comment]
Done, please have a look.
I didn't know how to do it without covering the calendar but you know it is a pop up so...

**Comment by rrd108** [comment]
I moved it to its dedicated frame.

I think the featured event text should be change to the actual event's name in this case

**Comment by rrd108** [comment]
@Sukhayanti took out the calendar view, it felt redundant and I really didn't like the design. I can put it back in if you think it is helpful but I will change the design. We have a calendar view on the programok page
