### ISSUE TITLE
minden lap alsó "érdekelhet még" blokba milyen linkek kerüljenek

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#71]

**Comment by Kundalata** [comment]
először az oldalt írom, és utána az Érdekelhet még... LINK oldalát...

egyéni jegyek -  programok
csoportok - útvonal
nyitvatartás - egyéni jegyek
Házirend - programok
Programok - egyéni jegyek
étterem - rólunk
útvonal - egyéni jegyek
