### ISSUE TITLE
2025 turisztikai rendezvények anyaga - drive-on, link a leírásban..

### ISSUE THREAD

**Issue by Kundalata** [rrd108/krisnavolgy#78]
https://drive.google.com/drive/folders/1d6MAz3IbiKMq3U0BshdPApgz78XyQ1mE?usp=sharing

**Comment by rrd108** [comment]
Szuper

Szóljon ha megvan, hogy melyik kép hova menjen.

**Comment by Kundalata** [comment]
Mindegyik fesztiválhoz külön mappában van:
1 db fő kép ami fekvő, keskenyebb, azonos méretű (cover névvel) a programok részhez
itt szövegek illetve video linkek is vannak. 

A mappákban lévő többi kép mehet arra az oldalra, ahol a szöveges leírás és a videó linkek meg részletes programok lesznek majd


https://drive.google.com/drive/folders/1d6MAz3IbiKMq3U0BshdPApgz78XyQ1mE?usp=sharing

**Comment by rrd108** [comment]
Elkészült ehhez az admin, szóval meg tudja Ön csinálni ezeket, vagy ki tudja adni valakinek.
