### ISSUE TITLE
Main menu 

### ISSUE THREAD

**Issue by rrd108** [rrd108/krisnavolgy#9]
Finalizing how many menu items we have, how many levels

**Comment by Sukhayanti** [comment]
Menu has 7 items:

1. Látogatás
2. Programok
3. Szállás
4. Étterem
5. Webshop
6. Rólunk
7. Kapcsolat

There are 3 levels

**Comment by rrd108** [comment]
3 levels is not good. People get confused. We have to find another solution.

**Comment by rrd108** [comment]
Is it already on figma?

**Comment by Sukhayanti** [comment]
Yes, you maped it out and it looks correct
